---@class CodeShapeIndexer
local M = {}

local util = require("code-shape.util")
local rpc = require("code-shape.rpc")
local roots = require("code-shape.roots")
local metrics = require("code-shape.metrics")
local uv = vim.uv

-- Alias for convenience
local safe_stop_timer = util.safe_stop_timer

---@type table<integer, boolean>
local indexed_buffers = {}

---@type table<string, boolean>
local indexed_uris = {}

---@type boolean
local workspace_indexed = false

---@type integer
local workspace_run_id = 0

---@type { id: integer }|nil
local workspace_job = nil

---@type fun(err: string|nil, result: table|nil)[]
local workspace_callbacks = {}

---@alias CodeShapeBufferIndexStatus "indexed"|"empty"|"error"|"skipped"
---@class CodeShapeBufferIndexResult
---@field status CodeShapeBufferIndexStatus
---@field symbol_count integer
---@field method "lsp"|"treesitter"|nil
---@field error string|nil
---@field bufnr integer
---@field uri string

-- Debounce state for each buffer
---@type table<integer, { timer: uv_timer_t|nil, pending: boolean, callbacks: fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)[] }>
local debounce_state = {}
local DEBOUNCE_MS = 150

---@type table<string, table<string, vim.treesitter.Query|false>>
local treesitter_query_cache = {}

local WORKSPACE_EMPTY_QUERY = ""
local WORKSPACE_FALLBACK_QUERIES = { "a", "e", "i", "o", "u", "s", "t", "_" }

---@param lang string
---@param query_str string
---@return vim.treesitter.Query|nil
local function get_cached_treesitter_query(lang, query_str)
  if type(lang) ~= "string" or lang == "" then
    return nil
  end

  local by_lang = treesitter_query_cache[lang]
  if not by_lang then
    by_lang = {}
    treesitter_query_cache[lang] = by_lang
  end

  local cached = by_lang[query_str]
  if cached ~= nil then
    return cached or nil
  end

  local ok, parsed = pcall(vim.treesitter.query.parse, lang, query_str)
  if not ok or not parsed then
    by_lang[query_str] = false
    return nil
  end

  by_lang[query_str] = parsed
  return parsed
end

---Check if result is DocumentSymbol[] (has range field) or SymbolInformation[] (has location field)
---@param result table
---@return boolean is_document_symbol
local function is_document_symbol_result(result)
  if not result or #result == 0 then
    return true -- Default to DocumentSymbol
  end
  local first = result[1]
  return first.range ~= nil
end

---Convert LSP DocumentSymbol to CodeShapeSymbol
---@param lsp_symbol table LSP DocumentSymbol
---@param uri string
---@return CodeShapeSymbol
local function lsp_to_symbol(lsp_symbol, uri)
  local range = {
    start = {
      line = lsp_symbol.range and lsp_symbol.range.start and lsp_symbol.range.start.line or 0,
      character = lsp_symbol.range and lsp_symbol.range.start and lsp_symbol.range.start.character or 0,
    },
    ["end"] = {
      line = lsp_symbol.range and lsp_symbol.range["end"] and lsp_symbol.range["end"].line or 0,
      character = lsp_symbol.range and lsp_symbol.range["end"] and lsp_symbol.range["end"].character or 0,
    },
  }

  local name = lsp_symbol.name or ""
  local kind = util.to_symbol_kind(lsp_symbol.kind)

  return {
    symbol_id = "", -- Generated by Rust core
    name = name,
    kind = kind,
    container_name = lsp_symbol.containerName,
    uri = uri,
    range = range,
    detail = lsp_symbol.detail,
  }
end

---Convert LSP SymbolInformation to CodeShapeSymbol
---SymbolInformation has a different structure: { name, kind, location: { uri, range }, containerName }
---@param lsp_symbol table LSP SymbolInformation
---@return CodeShapeSymbol|nil
local function lsp_symbol_info_to_symbol(lsp_symbol)
  -- Validate required fields
  if not lsp_symbol.name or not lsp_symbol.location then
    return nil
  end

  local location = lsp_symbol.location
  if not location.uri or not location.range then
    return nil
  end

  local range = {
    start = {
      line = location.range.start and location.range.start.line or 0,
      character = location.range.start and location.range.start.character or 0,
    },
    ["end"] = {
      line = location.range["end"] and location.range["end"].line or 0,
      character = location.range["end"] and location.range["end"].character or 0,
    },
  }

  local name = lsp_symbol.name
  local kind = util.to_symbol_kind(lsp_symbol.kind)

  return {
    symbol_id = "", -- Generated by Rust core
    name = name,
    kind = kind,
    container_name = lsp_symbol.containerName,
    uri = location.uri,
    range = range,
    detail = nil, -- SymbolInformation doesn't have detail
  }
end

---Clear debounce timer for a buffer
---@param bufnr integer
local function clear_debounce(bufnr)
  local state = debounce_state[bufnr]
  if state and state.timer then
    safe_stop_timer(state.timer)
    state.timer = nil
  end
end

---Request batch URI removal from core index
---@param uris string[]
local function remove_uris_batch(uris)
  if #uris == 0 then
    return
  end

  rpc.request("index/removeUris", { uris = uris }, function(err)
    if err then
      vim.notify("code-shape: " .. err, vim.log.levels.WARN)
    end
  end)
end

---@param callback function|nil
local function push_workspace_callback(callback)
  if callback then
    table.insert(workspace_callbacks, callback)
  end
end

---@param err string|nil
---@param result table|nil
local function flush_workspace_callbacks(err, result)
  local callbacks = workspace_callbacks
  workspace_callbacks = {}
  for _, cb in ipairs(callbacks) do
    cb(err, result)
  end
end

---@param run_id integer
---@return boolean
local function is_workspace_run_active(run_id)
  return workspace_job ~= nil and workspace_job.id == run_id
end

---@param run_id integer
---@param err string|nil
---@param result table|nil
local function finish_workspace_run(run_id, err, result)
  if not is_workspace_run_active(run_id) then
    return
  end
  workspace_job = nil
  if not err then
    workspace_indexed = true
  end
  flush_workspace_callbacks(err, result)
end

---@param callbacks fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)[]
---@param status CodeShapeBufferIndexStatus
---@param result CodeShapeBufferIndexResult
local function flush_buffer_callbacks(callbacks, status, result)
  for _, cb in ipairs(callbacks) do
    cb(status, result)
  end
end

---@param callback fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)|nil
---@param status CodeShapeBufferIndexStatus
---@param result CodeShapeBufferIndexResult
local function emit_buffer_callback(callback, status, result)
  if callback then
    callback(status, result)
  end
end

---@param bufnr integer
---@param uri string
---@param symbols CodeShapeSymbol[]
---@param method "lsp"|"treesitter"
---@param callback fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)|nil
local function upsert_symbols_for_buffer(bufnr, uri, symbols, method, callback)
  rpc.request("index/upsertSymbols", {
    uri = uri,
    symbols = symbols,
  }, function(upsert_err)
    if upsert_err then
      vim.notify("code-shape: " .. upsert_err, vim.log.levels.WARN)
      emit_buffer_callback(callback, "error", {
        status = "error",
        symbol_count = 0,
        method = method,
        error = upsert_err,
        bufnr = bufnr,
        uri = uri,
      })
      return
    end

    indexed_buffers[bufnr] = true
    indexed_uris[uri] = true
    roots.register_uri(uri)

    local status = #symbols > 0 and "indexed" or "empty"
    emit_buffer_callback(callback, status, {
      status = status,
      symbol_count = #symbols,
      method = method,
      error = nil,
      bufnr = bufnr,
      uri = uri,
    })
  end)
end

---Run the actual indexing after debounce
---@param bufnr integer
---@param callback fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)|nil
local function do_index_buffer(bufnr, callback)
  if not M.should_index(bufnr) then
    emit_buffer_callback(callback, "skipped", {
      status = "skipped",
      symbol_count = 0,
      method = nil,
      error = nil,
      bufnr = bufnr,
      uri = vim.uri_from_bufnr(bufnr) or "",
    })
    return
  end

  local uri = vim.uri_from_bufnr(bufnr)

  -- Get LSP clients for buffer
  local clients = vim.lsp.get_clients({ bufnr = bufnr })
  if not clients or #clients == 0 then
    -- Fallback to tree-sitter if no LSP clients
    M.index_with_treesitter(bufnr, uri, callback)
    return
  end

  -- Try to get document symbols from LSP
  local params = { textDocument = vim.lsp.util.make_text_document_params(bufnr) }

  local has_symbol_provider = false
  for _, client in ipairs(clients) do
    if client.server_capabilities.documentSymbolProvider then
      has_symbol_provider = true
      client:request("textDocument/documentSymbol", params, function(err, result)
        if err or not result then
          -- Fallback to tree-sitter on LSP error
          M.index_with_treesitter(bufnr, uri, callback)
          return
        end

        local symbols = {}

        -- Check if result is DocumentSymbol[] or SymbolInformation[]
        if is_document_symbol_result(result) then
          -- Process DocumentSymbol[] (hierarchical)
          local function process_document_symbols(symbols_list)
            for _, sym in ipairs(symbols_list) do
              table.insert(symbols, lsp_to_symbol(sym, uri))
              -- Process children recursively
              if sym.children and #sym.children > 0 then
                process_document_symbols(sym.children)
              end
            end
          end
          process_document_symbols(result)
        else
          -- Process SymbolInformation[] (flat with location)
          for _, sym in ipairs(result) do
            local symbol = lsp_symbol_info_to_symbol(sym)
            if symbol then
              table.insert(symbols, symbol)
            end
          end
        end

        -- Attach metrics from tree-sitter if available (gated by metrics.enabled)
        local code_shape = require("code-shape")
        local config = code_shape.get_config()
        if not config or config.metrics.enabled then
          local has_parser, ts_parser = pcall(vim.treesitter.get_parser, bufnr)
          if has_parser and ts_parser then
            local ts_lang = ts_parser:lang()
            for _, sym in ipairs(symbols) do
              if metrics.is_computable_kind(sym.kind) then
                sym.metrics = metrics.compute_for_range(bufnr, ts_lang, sym.range)
              end
            end
          end
        end

        upsert_symbols_for_buffer(bufnr, uri, symbols, "lsp", callback)
      end, bufnr)
      break -- Only need one LSP client
    end
  end

  -- Fallback to tree-sitter if no LSP client supports documentSymbol
  if not has_symbol_provider then
    M.index_with_treesitter(bufnr, uri, callback)
  end
end

---Check if buffer should be indexed
---@param bufnr integer
---@return boolean
function M.should_index(bufnr)
  if not vim.api.nvim_buf_is_valid(bufnr) then
    return false
  end

  local buftype = vim.bo[bufnr].buftype
  if buftype ~= "" then
    return false
  end

  local ft = vim.bo[bufnr].filetype
  -- Skip special buffers
  if ft == "" or ft == "NvimTree" or ft == "TelescopePrompt" or ft == "qf" then
    return false
  end

  local name = vim.api.nvim_buf_get_name(bufnr)
  if name == "" then
    return false
  end
  local stat = uv.fs_stat(name)
  if not stat or stat.type ~= "file" then
    return false
  end

  -- Check if buffer has a file
  local uri = vim.uri_from_bufnr(bufnr)
  if not uri or uri == "" or not uri:match("^file://") then
    return false
  end
  return true
end

---Index a single buffer
---@param bufnr integer
---@param callback? fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)
---@param opts? { immediate?: boolean }
function M.index_buffer(bufnr, callback, opts)
  opts = opts or {}

  if not M.should_index(bufnr) then
    emit_buffer_callback(callback, "skipped", {
      status = "skipped",
      symbol_count = 0,
      method = nil,
      error = nil,
      bufnr = bufnr,
      uri = vim.uri_from_bufnr(bufnr) or "",
    })
    return
  end

  -- Initialize debounce state if needed
  if not debounce_state[bufnr] then
    debounce_state[bufnr] = { timer = nil, pending = false, callbacks = {} }
  end

  local state = debounce_state[bufnr]
  if callback then
    table.insert(state.callbacks, callback)
  end

  if opts.immediate then
    clear_debounce(bufnr)
    state.pending = false

    local callbacks = state.callbacks
    state.callbacks = {}
    local forward = #callbacks > 0
        and function(status, result)
          flush_buffer_callbacks(callbacks, status, result)
        end
      or nil

    do_index_buffer(bufnr, forward)
    return
  end

  -- Mark as pending
  state.pending = true

  -- Clear existing timer
  if state.timer then
    if not state.timer:is_closing() then
      state.timer:stop()
    end
  else
    state.timer = uv.new_timer()
    if state.timer then
      pcall(function()
        state.timer:unref()
      end)
    else
      state.pending = false
      local callbacks = state.callbacks
      state.callbacks = {}
      do_index_buffer(bufnr, #callbacks > 0 and function(status, result)
        flush_buffer_callbacks(callbacks, status, result)
      end or nil)
      return
    end
  end

  -- Start debounce timer
  if state.timer then
    state.timer:start(DEBOUNCE_MS, 0, function()
      vim.schedule(function()
        if not state.pending then
          return
        end

        state.pending = false
        local callbacks = state.callbacks
        state.callbacks = {}
        local forward = #callbacks > 0
            and function(status, result)
              flush_buffer_callbacks(callbacks, status, result)
            end
          or nil

        if vim.api.nvim_buf_is_valid(bufnr) then
          do_index_buffer(bufnr, forward)
        else
          if forward then
            forward("skipped", {
              status = "skipped",
              symbol_count = 0,
              method = nil,
              error = nil,
              bufnr = bufnr,
              uri = "",
            })
          end
        end
      end)
    end)
  end
end

---Cleanup buffer from index
---@param bufnr integer
function M.cleanup_buffer(bufnr)
  -- Clear debounce timer
  clear_debounce(bufnr)
  debounce_state[bufnr] = nil

  local uri = vim.uri_from_bufnr(bufnr)
  if indexed_uris[uri] then
    rpc.request("index/removeUri", { uri = uri }, function() end)
    indexed_uris[uri] = nil
  end
  indexed_buffers[bufnr] = nil
end

---Reindex all opened buffers
---@param callback? fun(summary: { target_count: integer, indexed_count: integer, empty_count: integer, failed_count: integer, skipped_count: integer })
---@param opts? { immediate?: boolean }
function M.reindex_all(callback, opts)
  -- Clear current index
  local uris = {}
  for uri in pairs(indexed_uris) do
    table.insert(uris, uri)
  end
  remove_uris_batch(uris)
  indexed_uris = {}
  indexed_buffers = {}

  local summary = {
    target_count = 0,
    indexed_count = 0,
    empty_count = 0,
    failed_count = 0,
    skipped_count = 0,
  }
  local pending = 0

  local function complete_one(status)
    if status == "indexed" then
      summary.indexed_count = summary.indexed_count + 1
    elseif status == "empty" then
      summary.empty_count = summary.empty_count + 1
    elseif status == "error" then
      summary.failed_count = summary.failed_count + 1
    else
      summary.skipped_count = summary.skipped_count + 1
    end

    pending = pending - 1
    if pending == 0 and callback then
      callback(summary)
    end
  end

  -- Reindex all valid buffers
  for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
    if M.should_index(bufnr) then
      summary.target_count = summary.target_count + 1
      pending = pending + 1
      M.index_buffer(bufnr, function(status, _result)
        complete_one(status)
      end, opts)
    end
  end

  if pending == 0 and callback then
    callback(summary)
  end
end

---Clear all indexed data
function M.clear_all()
  -- Clear all debounce timers
  for bufnr in pairs(debounce_state) do
    clear_debounce(bufnr)
  end
  debounce_state = {}

  if workspace_job then
    workspace_job = nil
    flush_workspace_callbacks("workspace indexing cancelled", nil)
  end

  local uris = {}
  for uri in pairs(indexed_uris) do
    table.insert(uris, uri)
  end
  remove_uris_batch(uris)
  indexed_uris = {}
  indexed_buffers = {}
  workspace_indexed = false
end

---Index workspace symbols using LSP workspace/symbol
---This collects symbols from the entire workspace, not just opened buffers
---@param callback function|nil Optional callback called when indexing is complete
---@param opts? { restart?: boolean, fallback_queries?: string[] }
function M.index_workspace(callback, opts)
  opts = opts or {}

  if workspace_indexed and not opts.restart then
    if callback then
      callback(nil, { already_indexed = true })
    end
    return
  end

  if workspace_job then
    if opts.restart then
      M.cancel_workspace_index("workspace indexing cancelled (restarted)")
    else
      push_workspace_callback(callback)
      return
    end
  end

  local clients = vim.lsp.get_clients()
  if not clients or #clients == 0 then
    if callback then
      callback("No LSP clients available", nil)
    end
    return
  end

  local supporting_clients = {}
  for _, client in ipairs(clients) do
    if client.server_capabilities.workspaceSymbolProvider then
      table.insert(supporting_clients, client)
    end
  end

  if #supporting_clients == 0 then
    if callback then
      callback("No LSP client supports workspace/symbol", nil)
    end
    return
  end

  push_workspace_callback(callback)

  workspace_run_id = workspace_run_id + 1
  local run_id = workspace_run_id
  workspace_job = { id = run_id }
  local fallback_queries = vim.deepcopy(opts.fallback_queries or WORKSPACE_FALLBACK_QUERIES)

  local pending_count = #supporting_clients
  local total_symbols = 0
  local errors = {}
  local failed_clients = 0
  local total_queries = 0
  local fallback_used = false

  local function complete_client(client_failed)
    if client_failed then
      failed_clients = failed_clients + 1
    end
    pending_count = pending_count - 1
    if pending_count > 0 then
      return
    end

    if failed_clients == #supporting_clients then
      finish_workspace_run(run_id, table.concat(errors, "; "), nil)
      return
    end

    finish_workspace_run(run_id, nil, {
      symbol_count = total_symbols,
      errors = errors,
      query_count = total_queries,
      fallback_used = fallback_used,
    })
  end

  ---@param symbol CodeShapeSymbol
  ---@return string
  local function workspace_symbol_key(symbol)
    local start_line = symbol.range and symbol.range.start and symbol.range.start.line or 0
    local start_char = symbol.range and symbol.range.start and symbol.range.start.character or 0
    local end_line = symbol.range and symbol.range["end"] and symbol.range["end"].line or 0
    local end_char = symbol.range and symbol.range["end"] and symbol.range["end"].character or 0
    return table.concat({
      symbol.uri,
      symbol.name,
      tostring(symbol.kind),
      tostring(start_line),
      tostring(start_char),
      tostring(end_line),
      tostring(end_char),
    }, "|")
  end

  for _, client in ipairs(supporting_clients) do
    local queries = { WORKSPACE_EMPTY_QUERY }
    local query_index = 1
    local has_success_response = false
    local has_request_error = false
    local has_upsert_error = false
    local fallback_added = false
    local collected_symbols = {}
    local seen_symbols = {}

    local function add_symbols(result)
      if type(result) ~= "table" then
        return
      end

      for _, sym in ipairs(result) do
        local symbol = lsp_symbol_info_to_symbol(sym)
        if symbol then
          local key = workspace_symbol_key(symbol)
          if not seen_symbols[key] then
            seen_symbols[key] = true
            table.insert(collected_symbols, symbol)
          end
        end
      end
    end

    local function finalize_client()
      if not is_workspace_run_active(run_id) then
        return
      end

      local by_uri = {}
      for _, symbol in ipairs(collected_symbols) do
        if not by_uri[symbol.uri] then
          by_uri[symbol.uri] = {}
        end
        table.insert(by_uri[symbol.uri], symbol)
      end

      local upsert_pending = 0
      for uri, uri_symbols in pairs(by_uri) do
        upsert_pending = upsert_pending + 1
        total_symbols = total_symbols + #uri_symbols
        rpc.request("index/upsertSymbols", {
          uri = uri,
          symbols = uri_symbols,
        }, function(upsert_err)
          if not is_workspace_run_active(run_id) then
            return
          end

          if upsert_err then
            has_upsert_error = true
            table.insert(errors, upsert_err)
          else
            indexed_uris[uri] = true
            roots.register_uri(uri)
          end

          upsert_pending = upsert_pending - 1
          if upsert_pending == 0 then
            complete_client((has_request_error and not has_success_response) or has_upsert_error)
          end
        end)
      end

      if upsert_pending == 0 then
        complete_client((has_request_error and not has_success_response) or has_upsert_error)
      end
    end

    local function request_next()
      if query_index > #queries then
        finalize_client()
        return
      end

      local query = queries[query_index]
      query_index = query_index + 1
      total_queries = total_queries + 1

      client:request("workspace/symbol", { query = query }, function(err, result)
        if not is_workspace_run_active(run_id) then
          return
        end

        if err then
          has_request_error = true
          table.insert(errors, err.message or "Unknown error")
          request_next()
          return
        end

        has_success_response = true
        add_symbols(result)
        if query == WORKSPACE_EMPTY_QUERY and #collected_symbols == 0 and not fallback_added then
          fallback_added = true
          for _, fallback_query in ipairs(fallback_queries) do
            if type(fallback_query) == "string" and fallback_query ~= "" then
              table.insert(queries, fallback_query)
              fallback_used = true
            end
          end
        end

        request_next()
      end)
    end

    request_next()
  end
end

---Check if workspace has been indexed
---@return boolean
function M.is_workspace_indexed()
  return workspace_indexed
end

---Check if workspace indexing is currently running
---@return boolean
function M.is_workspace_indexing()
  return workspace_job ~= nil
end

---Reset workspace indexed flag (for reindexing)
function M.reset_workspace_indexed()
  workspace_indexed = false
end

---Cancel in-progress workspace indexing
---@param reason? string
---@return boolean cancelled
function M.cancel_workspace_index(reason)
  if not workspace_job then
    return false
  end

  workspace_job = nil
  workspace_indexed = false
  flush_workspace_callbacks(reason or "workspace indexing cancelled", nil)
  return true
end

---Index buffer using tree-sitter (fallback when LSP is not available)
---@param bufnr integer
---@param uri string
---@param callback? fun(status: CodeShapeBufferIndexStatus, result: CodeShapeBufferIndexResult)
function M.index_with_treesitter(bufnr, uri, callback)
  local has_parser, parser = pcall(vim.treesitter.get_parser, bufnr)
  if not has_parser or not parser then
    emit_buffer_callback(callback, "error", {
      status = "error",
      symbol_count = 0,
      method = "treesitter",
      error = "tree-sitter parser unavailable",
      bufnr = bufnr,
      uri = uri,
    })
    return
  end

  local code_shape = require("code-shape")
  local config = code_shape.get_config()
  local metrics_enabled = not config or config.metrics.enabled

  local symbols = {}
  local trees = parser:parse()
  if type(trees) ~= "table" or trees[1] == nil then
    emit_buffer_callback(callback, "error", {
      status = "error",
      symbol_count = 0,
      method = "treesitter",
      error = "tree-sitter parse failed",
      bufnr = bufnr,
      uri = uri,
    })
    return
  end

  local root = trees[1]
  local ok_root, root_node = pcall(function()
    return root:root()
  end)
  if not ok_root or not root_node then
    emit_buffer_callback(callback, "error", {
      status = "error",
      symbol_count = 0,
      method = "treesitter",
      error = "tree-sitter root unavailable",
      bufnr = bufnr,
      uri = uri,
    })
    return
  end
  local root_end_row
  local ok_end_row, end_row = pcall(function()
    return select(1, root_node:end_())
  end)
  if ok_end_row and type(end_row) == "number" then
    root_end_row = end_row
  end

  -- Query for common symbol types (function, method, class, etc.)
  -- This is a simplified query that works for many languages
  local queries = {
    -- Functions and methods
    [[
      (function_declaration name: (identifier) @name) @symbol
      (function_definition name: (identifier) @name) @symbol
      (method_declaration name: (field_identifier) @name) @symbol
      (method_definition name: (property_identifier) @name) @symbol
    ]],
    -- Classes and interfaces
    [[
      (class_declaration name: (type_identifier) @name) @symbol
      (class_definition name: (type_identifier) @name) @symbol
      (interface_declaration name: (type_identifier) @name) @symbol
    ]],
    -- Variables and constants
    [[
      (variable_declarator name: (identifier) @name) @symbol
      (const_declaration (identifier) @name) @symbol
    ]],
  }

  -- Try each query
  local lang = parser:lang()
  for _, query_str in ipairs(queries) do
    local query = get_cached_treesitter_query(lang, query_str)
    if query then
      ---@param match table
      ---@param capture_name string
      ---@return TSNode|nil
      local function resolve_capture_node(match, capture_name)
        local captures = query.captures or {}
        local direct = match[capture_name]
        if direct ~= nil then
          if type(direct) == "table" then
            return direct[1]
          end
          return direct
        end

        for capture_id, node in pairs(match) do
          local capture = captures[capture_id] or captures[capture_id + 1]
          if type(capture_id) == "number" and capture == capture_name then
            if type(node) == "table" then
              return node[1]
            end
            return node
          end
        end

        return nil
      end

      for _, match, _ in query:iter_matches(root_node, bufnr, 0, root_end_row, { all = true }) do
        local name_node = resolve_capture_node(match, "name")
        local symbol_node = resolve_capture_node(match, "symbol")

        if name_node and symbol_node then
          local name = vim.treesitter.get_node_text(name_node, bufnr)
          local start_line, _, end_line, end_col = symbol_node:range()

          -- Determine kind based on node type
          local node_type = symbol_node:type()
          local kind = 13 -- Default: Variable
          if node_type:find("function") or node_type:find("method") then
            kind = 12 -- Function
          elseif node_type:find("class") then
            kind = 5 -- Class
          elseif node_type:find("interface") then
            kind = 23 -- Interface
          end

          local range = {
            start = {
              line = start_line,
              character = 0,
            },
            ["end"] = {
              line = end_line or start_line,
              character = end_col or 0,
            },
          }

          local symbol_metrics = nil
          if metrics_enabled and metrics.is_computable_kind(kind) then
            symbol_metrics = metrics.compute(bufnr, lang, symbol_node)
          end

          table.insert(symbols, {
            symbol_id = "", -- Generated by Rust core
            name = name,
            kind = kind,
            container_name = nil,
            uri = uri,
            range = range,
            detail = nil,
            metrics = symbol_metrics,
          })
        end
      end
    end
  end

  upsert_symbols_for_buffer(bufnr, uri, symbols, "treesitter", callback)
end

return M
